/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 MoonLanding.glb --transform
Author: BlackProject (https://sketchfab.com/BlackProject)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-landing-67e8a3ea5fbe42f4a6cb6c96cf406df4
Title: 🌙 Moon Landing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function MoonLanding(props) {
  const { nodes, materials } = useGLTF('/moon-landing-optimized.glb')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 6.37, 0]}>
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_1.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_2.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_3.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_4.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_5.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_6.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_7.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_8.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_9.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_10.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_11.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_12.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_13.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_14.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_15.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_16.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_17.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_18.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_19.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_20.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_21.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_22.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_23.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_24.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_25.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_26.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_27.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_28.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_29.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_30.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_31.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_32.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_33.geometry} material={materials.Moon_Surface} />
            <mesh receiveShadow geometry={nodes.Moon_Surface_Moon_Surface_0_34.geometry} material={materials.Moon_Surface} />
          </group>
          <group position={[2.19, 1.16, 38.92]}>
            <group position={[-5.5, -0.11, 25.79]}>
              <mesh geometry={nodes.Lunar_Rock_5_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[1.55, -0.1, -2.22]} rotation={[0, 0.44, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-3.05, -0.04, 1.47]} />
              <mesh geometry={nodes.Lunar_Rock_3_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[0.29, 0.04, 3.03]} rotation={[0, 0.5, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[2.85, 0.48, -0.1]} rotation={[0, 0.72, 0]} />
              <mesh geometry={nodes.Lunar_Rock_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-1.63, -0.39, -2.18]} />
            </group>
            <group position={[-24.47, -0.11, 56.22]}>
              <mesh geometry={nodes.Lunar_Rock_5_2_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[1.55, -0.1, -2.22]} rotation={[0, 0.44, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_2_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-3.05, -0.04, 1.47]} />
              <mesh geometry={nodes.Lunar_Rock_3_2_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[0.29, 0.04, 3.03]} rotation={[0, 0.5, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_2_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[2.85, 0.48, -0.1]} rotation={[0, 0.72, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_3_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-1.63, -0.39, -2.18]} />
            </group>
            <group position={[4.63, -0.11, 68.15]}>
              <mesh geometry={nodes.Lunar_Rock_5_3_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[1.55, -0.1, -2.22]} rotation={[0, 0.44, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_3_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-3.05, -0.04, 1.47]} />
              <mesh geometry={nodes.Lunar_Rock_3_3_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[0.29, 0.04, 3.03]} rotation={[0, 0.5, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_4_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[2.85, 0.48, -0.1]} rotation={[0, 0.72, 0]} />
              <mesh geometry={nodes.Lunar_Rock_3_4_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-1.63, -0.39, -2.18]} />
            </group>
            <group position={[65.15, -0.36, -129.56]}>
              <mesh geometry={nodes.Lunar_Rock_5_4_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[1.55, -0.1, -2.22]} rotation={[0, 0.44, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_4_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-3.05, -0.04, 1.47]} />
              <mesh geometry={nodes.Lunar_Rock_3_5_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[0.29, 0.04, 3.03]} rotation={[0, 0.5, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_5_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[2.85, 0.48, -0.1]} rotation={[0, 0.72, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_5_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-1.63, -0.39, -2.18]} />
            </group>
            <group position={[-39.81, 0.7, -20.61]}>
              <mesh geometry={nodes.Lunar_Rock_5_5_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[1.55, -0.1, -2.22]} rotation={[0, 0.44, 0]} />
              <mesh geometry={nodes.Lunar_Rock_4_6_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-3.05, -0.04, 1.47]} />
              <mesh geometry={nodes.Lunar_Rock_3_6_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[0.29, 0.04, 3.03]} rotation={[0, 0.5, 0]} />
              <mesh geometry={nodes.Lunar_Rock_2_6_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[2.85, 0.48, -0.1]} rotation={[0, 0.72, 0]} />
              <mesh geometry={nodes.Lunar_Rock_5_6_Lunar_Rocks_0.geometry} material={materials.Lunar_Rocks} position={[-1.63, -0.39, -2.18]} />
            </group>
          </group>
          <group position={[-1.5, 0.97, 85.86]} rotation={[0, -0.62, 0]}>
            <mesh castShadow geometry={nodes.Aluminium_Capsule_Aluminium_Capsule_0.geometry} material={materials.Aluminium_Capsule} />
            <mesh castShadow geometry={nodes.Darker_Aluminium_Darker_Aluminium_0.geometry} material={materials.Darker_Aluminium} />
            <mesh castShadow geometry={nodes.Aluminium_Pieces_Aluminium_Pieces_0.geometry} material={materials.Aluminium_Pieces} />
            <mesh castShadow geometry={nodes.Aluminium_Pieces_Aluminium_Pieces_0_1.geometry} material={materials.Aluminium_Pieces} />
            <mesh castShadow geometry={nodes.Gold_Gold_0.geometry} material={materials.Gold} />
            <mesh castShadow geometry={nodes.Window_Window_0.geometry} material={materials.Window} />
          </group>
          {/* <group position={[1.98, 14.83, -18.74]}>
            <mesh castShadow geometry={nodes.Flag_Cloth_Flag_Cloth_0.geometry} material={materials.Flag_Cloth} position={[1.97, 3.94, -0.09]} />
            <mesh castShadow geometry={nodes.Flag_Base_Flag_Base_0.geometry} material={materials.Flag_Base} position={[-1.98, -3.94, 0.03]} />
          </group> */}
          <group position={[-37.59, 1.23, 17.96]}>
            <mesh castShadow geometry={nodes.gaskets_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.fabric_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.limbs_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.visor_Visor_0.geometry} material={materials.Visor} />
            <mesh castShadow geometry={nodes.inner_visor_Shield_0.geometry} material={materials.Shield} />
            <mesh castShadow geometry={nodes.helmet_top_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.head_light_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.pack_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.regulator_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.insert_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.torso_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.logo_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.flag_Suit_0.geometry} material={materials.Suit} />
          </group>
          <group position={[66.93, 0.49, -91.24]}>
            <mesh castShadow geometry={nodes.gaskets_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.fabric_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.limbs_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.visor_2_Visor_0.geometry} material={materials.Visor} />
            <mesh castShadow geometry={nodes.inner_visor_2_Shield_0.geometry} material={materials.Shield} />
            <mesh castShadow geometry={nodes.helmet_top_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.head_light_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.pack_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.regulator_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.insert_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.torso_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.logo_2_Suit_0.geometry} material={materials.Suit} />
            <mesh castShadow geometry={nodes.flag_2_Suit_0.geometry} material={materials.Suit} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/moon-landing-optimized.glb')
